### ISSUE TITLE
Templates and sample datasets

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/coldp#15]
@mdoering, I had a request from a data provider to add templates of the CoLDP flat and parent-child schemas in Excel. I have speadsheet templates already and could put them in a templates folder in this repo in xlsx and ods format. I could also create a Microsoft Access version, since Access is pretty commonly used. 

I could also post some small sample datasets of the two different schemas in other repos that we could link to in the readme.

- [x] MS Excel template flat
- [x] MS Excel template parent/child
- [x] MS Excel template NameUsage parent/child
- [ ] MS Access template flat 
- [ ] MS Access template parent/child
- [x] Postgres schema parent/child

**Comment by mdoering** [comment]
All really good ideas, yes!
Maybe a simple postgres schema is also worthwhile.
Lets create a templates folder and place it all in there, together with a readme that explains their usage and can link out to further examples. We can then link from the main readme to the templates one

**Comment by mdoering** [comment]
Postgres schemas added: https://github.com/CatalogueOfLife/coldp/blob/master/templates/schema-pg.sql
