### ISSUE TITLE
Add quadrinomial column?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/coldp#27]
ITIS has quadrinomials and their names are atomized. I could just add a "subInfraspecificEpithet" column in case quadrinomials are implemented at some point in the future.

In the past, CoL has just dropped quadrinomials, but maybe GBIF and other organizations would want them included?

**Comment by mdoering** [comment]
No, we also want to follow the code and just have 3 parted names.
In cases when the sources have 4 parted names I suggest to use the full name in scientificName and drop the superflous subspecies in the parsed fields. So you end up with the infraspecific epithet being the lowest rank, e.g. variety
