### ISSUE TITLE
Add accordingToDatabase to Taxon table?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/coldp#28]
For resources that include nested databases like ITIS, it would be good to add an accordingToDb field so that the nested databases can be properly credited. It might also be good to add an accordingToDbID with a link to the database citation information in the Reference table.

Alternatively, I could use the accordingTo field for database names, and maybe we should just add an accordingToReferenceID that allows additional citation info to be included for nested databases. The problem with that approach is that I will also have experts that should be listed in addition to the database, and it would be a mess to include experts and databases in the same accordingTo field.

**Comment by gdower** [comment]
On further thought, let me discuss this with ITIS first.

**Comment by mdoering** [comment]
I had very similar thoughts when thinking about how to export CoL as ColDP in our exports.
In Dwc we use a dwc:databaseID term for that. I like the idea of using a reference id for that. But maybe a dedicated datasource table makes more sense so we can a) keep the id and not mix it with reference ids and b) share more structured infos then the citation alone. Premature thinking at this stage though.
