### ISSUE TITLE
Ambiguity and possible inconsistency in reference elements in Name

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/coldp#36]
Name has the following elements:

* *referenceID* A pointer to a Reference indicating the original publication of the name in its given combination, not the basionym.
* *publishedInYear* The effective year the name was published, given as a 4 digit integer . This is the year that is nomenclaturally relevant.
* *publishedInPage* The exact single page number where the name was published. If the description spans multiple pages, the first page should be given.

For a combination, this is explicit that the referenceID should be for the location of the new combination. By implication, the same applies for the publishedInPage, although this should be made explicit in the documentation.

Does this mean that the publishedInYear should also be for the combination? If so, is the year really "nomenclaturally relevant"? 

The documentation needs to be made explicit and consistent.

**Comment by mdoering** [comment]
Yes, it definitely means the year of publication of that combination.
It is probably not relevant in zoology, but for botany I believe it is.

Any suggestion for a better wording?

**Comment by mdoering** [comment]
#### publishedInYear
> The effective year the name was published, given as a 4 digit integer. 
It is the year that is nomenclaturally relevant for the given combination.
In most cases this will be the same as the publication year given in the linked reference record via referenceID.
But in some cases this might be different.
