### ISSUE TITLE
gazetteer: add marineregions.org in vocab

### ISSUE THREAD

**Issue by bart-v** [CatalogueOfLife/coldp#39]
http://api.catalogue.life/vocab/gazetteer
should contain https://www.marineregions.org/gazetteer.php

**Comment by mdoering** [comment]
How would an example record look like?
Is `MRGID`  a good short name for the gazetteer with the title being `Marine Regions Geographic Identifier` ?

**Comment by bart-v** [comment]
MRGID is the name of the identifier used
Maybe make the short name "marineregions.org" and the full name "Marine Regions Gazetteer"

**Comment by mdoering** [comment]
How about `MRG` & `Marine Regions Gazetteer` otherwise?
See https://api.dev.catalogueoflife.org/vocab/gazetteer for others

**Comment by bart-v** [comment]
Yes, fine too
