### ISSUE TITLE
Supporting Ecological Metadata Language?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/coldp#43]
WoRMS has their metadata in Ecological Metadata Language (EML) format and was requesting that we consider allowing that as part of a CoLDP package instead of the metadata.yml. Does the DarwinCore importer already have EML parsing capability?

**Comment by mdoering** [comment]
Yes that would be possible. 
Although there are certain things in ColDP metadata that you cannot provide with EML, e.g. organisations & code.

I would prefer to secretly allow EML in the importer code, but not mention it in the ColDP specification.
I find the EML standard rather bloated and not at all easy to use.

**Comment by bart-v** [comment]
So, if we include it in the ZIP will it be parsed then?

**Comment by gdower** [comment]
Actually, maybe I can test it with this? https://api.gbif.org/v1/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527/document

**Comment by bart-v** [comment]
Yes, please, the other exports will be similar

**Comment by mdoering** [comment]
> So, if we include the EML in the ZIP will it be parsed then?

Yes. Did you try and had problems?
If you find surprises please make sure the EML alone is readable by COL by using the test service here:

http://api.dev.catalogueoflife.org/parser/metadata?format=eml&url=https%3A%2F%2Fapi.gbif.org%2Fv1%2Fdataset%2F2d59e5db-57ad-41ff-97d6-11f5fb264527%2Fdocument

In case we receive bad xml or have some other problem parsing the EML there will simply be no metadata applied. It is impossible (or at least very hard) to parse just parts of the XML successfully.

**Comment by mdoering** [comment]
I will move this issue to the implementation instead, it is mostly not ColDP specs related.
I don't think we should advertise EML in ColDP, it is too complex and it can be far more expressive and offering alternative ways of doing the same thing than what COL supports - it will rather be a hidden feature of the implementation.
