### ISSUE TITLE
Add tree branch length for phylogenies

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/coldp#55]
In order to support phylogenetic trees the main missing property is the branch or edge length of trees.
It is called `length` in the [Newick format](https://en.wikipedia.org/wiki/Newick_format):

> Length: the length of a tree edge.

[PhyloXML](https://en.wikipedia.org/wiki/PhyloXML) calls it `branch_length`.

Suggest to add a new field `parentLength` to the Taxon entity to indicate the length of the edge between a child and it's parent node. It will take a number (float).

The ability to indicate a unit of the length is likely important and should be added to the metadata.yaml as a new property. parentLengthUnit might be a good matching term.

**Comment by mdoering** [comment]
One reason to have this is being able to import oToL

**Comment by dhobern** [comment]
@mjy - I think the issues are clear and well understood. However, it certainly makes sense for COL ChecklistBank to accommodate branch length where included for any datasets it imports. These lengths will only be meaningful in the context of that dataset, but it will be much easier to get them early rather than expect data publishers to add them later.

**Comment by dhobern** [comment]
Thanks @mjy - I completely agree that we should not be seduced into thinking this supports downstream analysis without at least also focusing on a number of metadata aspects. I'm only seeing this as a way to preserve and visualise the outputs from the source studies to visualise their basis for asserting a hierarchy. All further interpretation would be via redirection to the source. This is not directly to support meta-analysis or synthesis. In a sense it's just metadata to justify the supplied list. We should require at least enough additional metadata to locate the source analysis.
