### ISSUE TITLE
Add Name. gender & genderAgreement

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/coldp#69]
Knowing the gender of a genus is crucial in understanding it's nomenclature.
The proposed new `gender` field should indicate the _gender of the genus name_ either given as a uninomial at generic rank or as a bi- or trinomial.

Values for the gender field should be one of `masculine`, `feminine` or `neuter`.

For the terminal epithet of bi- or trinomen it is also important to know whether the epithet has to follow the gender agreement: https://code.iczn.org/formation-and-treatment-of-names/article-31-species-group-names/?frame=1#
For this the boolean term genderAgreement is proposed.

**Comment by mdoering** [comment]
see https://code.iczn.org/formation-and-treatment-of-names/article-30-gender-of-genus-group-names/?frame=1

**Comment by mdoering** [comment]
@deepreef could you review this proposal and see if it makes sense?
Do we need to track the kind of word the epithet is based on or is it sufficient ot know the boolean needs to agree with genus?
> A species-group name formed from a personal name may be either a noun in the genitive case, or a noun in apposition (in the nominative case), or an adjective or participle

**Comment by deepreef** [comment]
@mdoering:  I think the most basic pieces of information needed are:
1) Gender of the genus (Masculine, Feminine, Neuter, Unknown)
2) Whether or not a species or subspecific epithet should be changed to match the gender of the genus.

In that context, I think the proposal is probably fine.  In my databases, I have explored the idea of more granular parsing of "word type" for epithets (e.g., noun, adjective for sure, but also things like "patronym" and "toponym" and such as well).

But for this context, I think all you really need to know is "Does the spelling of this epithet depend on the gender of the genus?", and this can probably be adequately represented by a boolean value (or, perhaps a Yes/No/Unknown value).

I hope that helps!

**Comment by mdoering** [comment]
Thanks @deepreef. As you might have guessed the latest Taxacom explosions have fueled up this issue.
