### ISSUE TITLE
proposal Add accepted name field in coldp

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/coldp#71]
In coldp the parentID connects synonyms names with the accepted name, although this works perfectly for the database  management, for publishers  preparing A coldp packag something more intuitive is neded to know the accepted name, I propose to add a field for the accepted name something like the [acceptedNameUsage](https://dwc.tdwg.org/terms/#dwc:acceptedNameUsage) in DwC.

**Comment by mdoering** [comment]
Although being practical for readability, it is introducing potential problems when the parentID and acceptedNameUsage do contradict. It is similar with the flat, higher rank terms (kingdom->subgenus), but these are harder to read as you have to go up potentially many, many records. And some people actually do not have any records for these higher taxa, so you cannot use parentID. But for the accepted name there will always be a taxon ID to link to.
