### ISSUE TITLE
Add TaxonProperty table to simplify sharing profiles and traits

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/coldp#76]
See: https://www.checklistbank.org/dataset/265709/taxon/422

This includes lots of other information in the taxon remarks field, but there is no way to structure it for reading or machine access.The only way really to include this data in a COLDP package today is as a set of treatment files. 

I propose a TaxonProperty table in COLDP so this information can be shared more reliably. 

This table could have the following columns: 

1. taxonID
2. categoryID (either a text label like "Biology" or "Illustration", or a Plinian core term)
3. categoryScheme (either "text" or "plinian")
4. property (free text)
5. referenceID
6. page
7. remarks

This would be flexible and would encourage me to normalise all this stuff much more (and make better use of the references).

**Comment by mdoering** [comment]
If the entity is called TaxonProperty would `property` & `value` not be good terms to be used?

1. taxonID
2. property (either a text label like "Biology" or "Illustration", a Plinian core term or some wikidata P value like [P2974](https://www.wikidata.org/wiki/Property:P2974))
3. value (free text)
4. referenceID
5. page
6. remarks

**Comment by dhobern** [comment]
Sounds good to me. I was trying to model it on the Distribution model, but this is easier.

**Comment by dhobern** [comment]
Note also that, if property can be a trait URI, we can support sharing of species trait datasets too.

**Comment by mdoering** [comment]
I can imagine having an `ordinal` to define the order of properties shown for taxa might be useful in some cases.
It would be optional, but allow to specify "chapters" that require specific ordering. Or is it better to require that no order can be assumed?

For the taxonomy we called it sequenceIndex - I would have preferred to call it ordinal these days. (maybe we can still change that? Noone apart from you, Donald, is actually using it so far)

**Comment by dhobern** [comment]
Sure - feel free to rename it

**Comment by mdoering** [comment]
Added to docs for the 1.1 release

**Comment by dhobern** [comment]
I'll try enriching the Hepialidae dataset accordingly. Thanks.

**Comment by mdoering** [comment]
CLB also reads DwC MeasurementAndFact & GBIF:Description records into the taxon property table

**Comment by mdoering** [comment]
is supported on dev now - but UI is still lacking, see https://github.com/CatalogueOfLife/checklistbank/issues/1298

**Comment by mdoering** [comment]
You can see the properties in the API either inside the complete taxon info object:
https://api.checklistbank.org/dataset/265709/taxon/422/info

Or directly just the property list:
https://api.checklistbank.org/dataset/265709/taxon/422/property

**Comment by mdoering** [comment]
here is a silly example dataset: https://www.dev.checklistbank.org/dataset/270538/verbatim?type=col:TaxonProperty

**Comment by mdoering** [comment]
https://api.dev.checklistbank.org/dataset/270538/taxon/1/info
https://api.dev.checklistbank.org/dataset/270538/taxon/1/property
